name: Build and Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: default_environment
    steps:
    - uses: actions/checkout@v3

    - name: Install Emacs
      run: sudo apt install emacs

    - name: Make FTP Username Available
      run: echo "${{ env.FTP_USERNAME }}" > ftp_username

    - name: Make FTP Password Available
      run: echo "${{ secrets.FTP_PASSWORD }}" > ftp_password

    - name: Build and Deploy
      run: make all
